In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/Users/josephyi/Downloads/csv_files/throwsh.csv')

In [31]:
# df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
idx = df.groupby(df['date'].dt.year)['vol'].idxmax()
nested_df1 = df.loc[idx, ['date', 'vol']].reset_index(drop=True)
nested_df1['date'] = nested_df1['date'].astype(str)
nested_df1

          date       vol
0   1997-07-10   7190075
1   1998-02-09   3968369
2   1999-07-07   6231927
3   2000-01-14   5259179
4   2001-10-11   7681942
5   2002-01-10   4323656
6   2003-08-27   6453973
7   2004-11-05  12269671
8   2005-02-18   9256851
9   2006-01-31  13121030
10  2007-12-21   4762132
11  2008-10-08   9739822
12  2009-01-07   7718665
13  2010-05-19   4731855
14  2011-11-21   7672480
15  2012-01-12   5346985
16  2013-06-21   4851686
17  2014-04-09   4868791
18  2015-01-14   3939615
19  2016-11-10   4233466
20  2017-01-12   3183435
21  2018-09-21   3796857
22  2019-01-09    804877

In [26]:
max_close = df.groupby(df['date'].dt.year)['close'].transform('max')
nested_df2 = df.loc[df['close']==max_close, ['date', 'close']].reset_index(drop=True)

In [30]:

def df_str(df):
    return df.to_string(index=True)

nested = [
    [nested_df1, nested_df2],
]

pretty = [[df_str(a), df_str(b)] for a, b in nested]
nested

[[          date       vol
  0   1997-07-10   7190075
  1   1998-02-09   3968369
  2   1999-07-07   6231927
  3   2000-01-14   5259179
  4   2001-10-11   7681942
  5   2002-01-10   4323656
  6   2003-08-27   6453973
  7   2004-11-05  12269671
  8   2005-02-18   9256851
  9   2006-01-31  13121030
  10  2007-12-21   4762132
  11  2008-10-08   9739822
  12  2009-01-07   7718665
  13  2010-05-19   4731855
  14  2011-11-21   7672480
  15  2012-01-12   5346985
  16  2013-06-21   4851686
  17  2014-04-09   4868791
  18  2015-01-14   3939615
  19  2016-11-10   4233466
  20  2017-01-12   3183435
  21  2018-09-21   3796857
  22  2019-01-09    804877,
           date     close
  0  1997-10-22    8.4273
  1  1998-02-09    5.4130
  2  1998-04-30    5.4130
  3  1999-07-09    9.8670
  4  2000-02-25   11.4410
  5  2001-01-29    8.7326
  6  2001-01-30    8.7326
  7  2002-01-22    5.9593
  8  2003-10-15    9.1826
  9  2004-10-11   13.3590
  10 2005-12-29   23.4350
  11 2006-05-11   49.1240
  12 2007-10-15   66.2150
  13 2008-02-27   51.8610
  14 2009-12-04   66.2720
  15 2010-12-31  106.8400
  16 2011-07-07  127.6300
  17 2011-07-15  127.6300
  18 2012-12-19  161.5100
  19 2013-01-03  160.6700
  20 2013-01-04  160.6700
  21 2014-08-27  129.7100
  22 2015-05-13  123.1300
  23 2016-12-08   97.0870
  24 2017-02-21  134.3100
  25 2018-01-15  115.0000
  26 2019-01-18   92.4800]]

In [34]:
pd.DataFrame([{'bedroom': 3, 'space': 1500}])

   bedroom  space
0        3   1500